% Build the FLIMreader MEX file in the current working directory

clear FLIMreaderMex
cdir = mfilename('fullpath');
cdir = strrep(cdir,'CompileFLIMreaderMex','');
cdir = [cdir 'Source' filesep];

boost_dir = '/usr/local/include';
boost_lib_dir = '"/usr/local/lib"';

mex([cdir 'FLIMreaderMex' filesep 'FLIMreaderMex.cpp'], ...
    [cdir 'FLIMReader' filesep 'AbstractPicoquantReader.cpp'], ...
    [cdir 'FLIMReader' filesep 'PicoquantTTRReader.cpp'], ...
    [cdir 'FLIMReader' filesep 'PicoquantPTUReader.cpp'], ...
    [cdir 'FLIMReader' filesep 'FLIMReader.cpp'], ...
    [cdir 'FLIMReader' filesep 'TextReader.cpp'], ...
    ['-I' cdir 'FLIMreader' ], ...
    ['-I' cdir 'FLIMreaderMex'], ...
    ['-I' boost_dir], ...
    ['-L' boost_lib_dir], ... 
    ['-l' 'boost_filesystem-mt'],...
    ['-l' 'boost_system-mt'],...
    'CXXFLAGS="$CXXFLAGS -std=c++11"');
