% Build the FLIMreader MEX file in the current working directory

dir = mfilename('fullpath');
dir = strrep(dir,'CompileFLIMreaderMex','');
dir = [dir 'Source' filesep];

mex([dir 'FLIMreaderMex/FLIMreaderMex.cpp'], ...
    [dir 'FLIMReader/PicoquantTTRReader.cpp'], ...
    ['-I' dir 'FLIMreader' ], ...
    ['-I' dir 'FLIMreaderMex'], ...
    'CXXFLAGS="$CXXFLAGS -std=c++11"');
